FROM node:10-alpine as angular

RUN apk add --update \
  python \
  make \
  g++

WORKDIR /usr/src/app

COPY ./angular .

RUN npm cache verify && npm ci
RUN npm rebuild node-sass

ENV PATH /usr/src/app/node_modules/.bin:$PATH

EXPOSE 80

CMD ["npm", "start"]
