version: "3"
services:
  web:
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./angular/:/usr/src/app/
      - /usr/src/app/node_modules/
